language: python

sudo: false

python:
  - 3.6

addons:
  apt:
    packages:
      - swig
      - libusb-1.0-0-dev

cache:
  pip: true
  apt: true
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox coveralls

env:
  - TOXENV=py36
  - TOXENV=py27

script: tox

after_success:
  - coveralls
